### ISSUE TITLE
Ruby 2 compatibility

### ISSUE THREAD

**Issue by attilaolah** [precipice/campfire_export#19]
Running `campfire_export` with Ruby 2.0 or 2.1 gives the following error:

> Unable to export account: can't convert Date into String

**Comment by attilaolah** [comment]
This seems to be caused by `crack`:

```
/home/attila/.gem/ruby/2.0.0/gems/crack-0.1.8/lib/crack/xml.rb:86:in `to_hash': can't modify frozen Fixnum (RuntimeError)
        from /home/attila/.gem/ruby/2.0.0/gems/crack-0.1.8/lib/crack/xml.rb:108:in `merge!'
        from /home/attila/.gem/ruby/2.0.0/gems/crack-0.1.8/lib/crack/xml.rb:108:in `block in to_hash'
        from /home/attila/.gem/ruby/2.0.0/gems/crack-0.1.8/lib/crack/xml.rb:106:in `each'
        from /home/attila/.gem/ruby/2.0.0/gems/crack-0.1.8/lib/crack/xml.rb:106:in `to_hash'
        from /home/attila/.gem/ruby/2.0.0/gems/crack-0.1.8/lib/crack/xml.rb:211:in `parse'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/parser.rb:112:in `xml'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/parser.rb:136:in `parse_supported_format'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/parser.rb:103:in `parse'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/parser.rb:66:in `call'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/request.rb:217:in `parse_response'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/request.rb:189:in `handle_response'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty/request.rb:71:in `perform'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty.rb:390:in `perform_request'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty.rb:342:in `get'
        from /home/attila/.gem/ruby/2.0.0/gems/httparty-0.7.8/lib/httparty.rb:422:in `get'
        from /home/attila/github.com/precipice/campfire_export/lib/campfire_export.rb:42:in `get'
        from /home/attila/github.com/precipice/campfire_export/lib/campfire_export.rb:146:in `find_timezone'
        from bin/campfire_export:58:in `<main>'
```

**Comment by attilaolah** [comment]
I think I should just get `crack` updated somehow. Maybe updating the gemspec would help.

Anyway, closing this as it is not relevant to `campfire_export`.
