### ISSUE TITLE
mapping values are not allowed in this context at line 4 column 52 (Psych::SyntaxError)

### ISSUE THREAD

**Issue by atorreso** [precipice/campfire_export#22]
I am getting the following when the app tries to download a .js file.

cust_service_djenga.js ... /usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): mapping values are not allowed in this context at line 4 column 52 (Psych::SyntaxError)
    from /usr/lib/ruby/1.9.1/psych.rb:203:in`parse_stream'
    from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
    from /usr/lib/ruby/1.9.1/psych.rb:127:in`load'
    from /var/lib/gems/1.9.1/gems/crack-0.1.8/lib/crack/json.rb:12:in `parse'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/parser.rb:116:in`json'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/parser.rb:136:in `parse_supported_format'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/parser.rb:103:in`parse'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/parser.rb:66:in `call'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/request.rb:217:in`parse_response'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/request.rb:189:in `handle_response'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty/request.rb:71:in`perform'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty.rb:390:in `perform_request'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty.rb:342:in`get'
    from /var/lib/gems/1.9.1/gems/httparty-0.7.8/lib/httparty.rb:422:in `get'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:42:in`get'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:463:in `export_content'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:436:in`export'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:289:in `block in export_uploads'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:286:in`each'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:286:in `export_uploads'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:235:in`export'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/lib/campfire_export.rb:177:in `export'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/bin/campfire_export:61:in`block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/bin/campfire_export:60:in `each'
    from /var/lib/gems/1.9.1/gems/campfire_export-0.3.0/bin/campfire_export:60:in`<top (required)>'
    from /usr/local/bin/campfire_export:23:in `load'
    from /usr/local/bin/campfire_export:23:in`<main>'

Outside of this, it works great, but when it hits the .js file it just dies.  

Thanks,

**Comment by jsl** [comment]
Hi @atorreso - I made several fixes and updates to this project, and now I'm unable to reproduce the issue you reported. Javascript files ending in .js download fine. It may be that the dependencies I upgraded fixed the issue you found, or that there was something peculiar about your file. 

At any rate, I'd be interested in hearing if you can still reproduce it using my fork ([GitHub](https://github.com/stackbuilders/campfire_export), [RubyGems](https://rubygems.org/gems/stackbuilders-campfire_export)).

Thanks for reporting this issue!
