### ISSUE TITLE
Incompatible version issues

### ISSUE THREAD

**Issue by kraviteja** [precipice/campfire_export#23]
I tried fixing around the version issue but I am still getting the below error. 

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/rbconfig.rb:212: warning: Insecure world writable dir /usr/local/ActivePerl-5.16/site in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': dlopen(/Users/Ravi/.rvm/gems/ruby-1.9.3-p545@global/gems/nokogiri-1.5.11/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: @@HOMEBREW_PREFIX@@/opt/libxml2/lib/libxml2.2.dylib (LoadError)
  Referenced from: /Users/Ravi/.rvm/gems/ruby-1.9.3-p545@global/gems/nokogiri-1.5.11/lib/nokogiri/nokogiri.bundle
  Reason: Incompatible library version: nokogiri.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 - /Users/Ravi/.rvm/gems/ruby-1.9.3-p545@global/gems/nokogiri-1.5.11/lib/nokogiri/nokogiri.bundle
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
    from /Users/Ravi/.rvm/gems/ruby-1.9.3-p545@global/gems/nokogiri-1.5.11/lib/nokogiri.rb:28:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/Ravi/.rvm/gems/ruby-1.9.3-p545@global/gems/campfire_export-0.3.0/lib/campfire_export.rb:30:in`<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
    from /Users/Ravi/.rvm/gems/ruby-1.9.3-p545@global/gems/campfire_export-0.3.0/bin/campfire_export:28:in `<top (required)>'
    from /usr/bin/campfire_export:23:in`load'
    from /usr/bin/campfire_export:23:in `<main>

**Comment by kraviteja** [comment]
I could finally fix it , is there a way where I can extract specific room, I am getting time out issue if i am extracting all the rooms
